title: The Equinox Project
description: Full ASP.NET Core 3.1 application with DDD, CQRS and Event Sourcing
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
